/**
 * @fileoverview Binaryen glue code for JavaScript.
 * @license Apache-2.0
 */

import binaryen from '../../lib/binaryen.js';

export const {
    _BinaryenTypeCreate,
    _BinaryenTypeArity,
    _BinaryenTypeExpand,
    _BinaryenTypeGetHeapType,
    _BinaryenTypeFromHeapType,
    _BinaryenTypeIsNullable,

    _BinaryenTypeInt32,
    _BinaryenTypeFuncref,
    _BinaryenTypeExternref,
    _BinaryenTypeAnyref,
    _BinaryenTypeEqref,
    _BinaryenTypeI31ref,
    _BinaryenTypeDataref,
    _BinaryenTypeArrayref,
    _BinaryenTypeStringref,
    _BinaryenTypeStringviewWTF8,
    _BinaryenTypeStringviewWTF16,
    _BinaryenTypeStringviewIter,
    _BinaryenTypeNullref,
    _BinaryenTypeNullExternref,
    _BinaryenTypeNullFuncref,

    _BinaryenPackedTypeNotPacked,
    _BinaryenPackedTypeInt8,
    _BinaryenPackedTypeInt16,

    _BinaryenHeapTypeFunc,
    _BinaryenHeapTypeExt,
    _BinaryenHeapTypeAny,
    _BinaryenHeapTypeEq,
    _BinaryenHeapTypeI31,
    _BinaryenHeapTypeData,
    _BinaryenHeapTypeArray,
    _BinaryenHeapTypeString,
    _BinaryenHeapTypeStringviewWTF8,
    _BinaryenHeapTypeStringviewWTF16,
    _BinaryenHeapTypeStringviewIter,
    _BinaryenHeapTypeNone,
    _BinaryenHeapTypeNoext,
    _BinaryenHeapTypeNofunc,

    _BinaryenHeapTypeIsBottom,
    _BinaryenHeapTypeGetBottom,
    _BinaryenHeapTypeIsSubType,
    _BinaryenStructTypeGetNumFields,
    _BinaryenStructTypeGetFieldType,
    _BinaryenStructTypeGetFieldPackedType,
    _BinaryenStructTypeIsFieldMutable,
    _BinaryenArrayTypeGetElementType,
    _BinaryenArrayTypeGetElementPackedType,
    _BinaryenArrayTypeIsElementMutable,
    _BinaryenSignatureTypeGetParams,
    _BinaryenSignatureTypeGetResults,

    _BinaryenStructNew,
    _BinaryenStructNewGetNumOperands,
    _BinaryenStructNewGetOperandAt,
    _BinaryenStructNewSetOperandAt,
    _BinaryenStructNewAppendOperand,
    _BinaryenStructNewInsertOperandAt,
    _BinaryenStructNewRemoveOperandAt,

    _BinaryenStructGet,
    _BinaryenStructGetGetIndex,
    _BinaryenStructGetSetIndex,
    _BinaryenStructGetGetRef,
    _BinaryenStructGetSetRef,
    _BinaryenStructGetIsSigned,
    _BinaryenStructGetSetSigned,

    _BinaryenStructSet,
    _BinaryenStructSetGetIndex,
    _BinaryenStructSetSetIndex,
    _BinaryenStructSetGetRef,
    _BinaryenStructSetSetRef,
    _BinaryenStructSetGetValue,
    _BinaryenStructSetSetValue,

    _BinaryenArrayNew,
    _BinaryenArrayNewGetInit,
    _BinaryenArrayNewSetInit,
    _BinaryenArrayNewGetSize,
    _BinaryenArrayNewSetSize,

    _BinaryenArrayInit,
    _BinaryenArrayInitGetNumValues,
    _BinaryenArrayInitGetValueAt,
    _BinaryenArrayInitSetValueAt,
    _BinaryenArrayInitAppendValue,
    _BinaryenArrayInitInsertValueAt,
    _BinaryenArrayInitRemoveValueAt,

    _BinaryenArrayGet,
    _BinaryenArrayGetGetRef,
    _BinaryenArrayGetSetRef,
    _BinaryenArrayGetGetIndex,
    _BinaryenArrayGetSetIndex,
    _BinaryenArrayGetIsSigned,
    _BinaryenArrayGetSetSigned,

    _BinaryenArraySet,
    _BinaryenArraySetGetRef,
    _BinaryenArraySetSetRef,
    _BinaryenArraySetGetIndex,
    _BinaryenArraySetSetIndex,
    _BinaryenArraySetGetValue,
    _BinaryenArraySetSetValue,

    _BinaryenArrayLen,
    _BinaryenArrayLenGetRef,
    _BinaryenArrayLenSetRef,

    _BinaryenArrayCopy,
    _BinaryenArrayCopyGetDestRef,
    _BinaryenArrayCopySetDestRef,
    _BinaryenArrayCopyGetDestIndex,
    _BinaryenArrayCopySetDestIndex,
    _BinaryenArrayCopyGetSrcRef,
    _BinaryenArrayCopySetSrcRef,
    _BinaryenArrayCopyGetSrcIndex,
    _BinaryenArrayCopySetSrcIndex,
    _BinaryenArrayCopyGetLength,
    _BinaryenArrayCopySetLength,

    _TypeBuilderCreate,
    _TypeBuilderGrow,
    _TypeBuilderGetSize,
    _TypeBuilderSetBasicHeapType,
    _TypeBuilderSetSignatureType,
    _TypeBuilderSetStructType,
    _TypeBuilderSetArrayType,
    _TypeBuilderIsBasic,
    _TypeBuilderGetBasic,
    _TypeBuilderGetTempHeapType,
    _TypeBuilderGetTempTupleType,
    _TypeBuilderGetTempRefType,
    _TypeBuilderSetSubType,
    _TypeBuilderCreateRecGroup,
    _TypeBuilderBuildAndDispose,
    _BinaryenModuleSetTypeName,
    _BinaryenModuleSetFieldName,

    _BinaryenRefEq,
    _BinaryenRefEqGetLeft,
    _BinaryenRefEqSetLeft,
    _BinaryenRefEqGetRight,
    _BinaryenRefEqSetRight,

    _malloc,
    _free,
    __i32_store8,
    __i32_store16,
    __i32_store,
    __f32_store,
    __f64_store,
    __i32_load8_s,
    __i32_load8_u,
    __i32_load16_s,
    __i32_load16_u,
    __i32_load,
    __f32_load,
    __f64_load,
} = binaryen;

export default binaryen;
